export const FETCH_CMSDATA_BEGIN = 'FETCH_CMSDATA_BEGIN';
export const FETCH_CMSDATA_SUCCESS = 'FETCH_CMSDATA_SUCCESS';
export const FETCH_CMSDATA_FAILURE = 'FETCH_CMSDATA_FAILURE';
export const ADD_CMSDATA = 'ADD_CMSDATA';
export const UPDATE_CMSDATA = 'UPDATE_CMSDATA';
